version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: angular-app-db
    restart: always
    environment:
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: Password1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:

